development:
  sessions:
    default:
      database: kulmong_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: kulmong_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>

  